language: generic

matrix:
  include:
    - &nvim
      env: EDITOR=nvim
      sudo: required
      dist: trusty

      before_script:
        # For: (12.04 14.04 15.04 15.10 16.04 16.10)
        - sudo apt-add-repository ppa:neovim-ppa/unstable -y
        - sudo apt-get update -qq
        - sudo apt-get install neovim

      script:
        - make travis

    - &vim73
      env: EDITOR=vim
      sudo: false
      addons:
        apt:
          packages:
          - vim

      script:
        - make travis

    - &vim74
      env: EDITOR=vim
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
          - vim

      script:
        - make travis

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
